# Generated by Django 3.2.25 on 2025-03-04 03:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "flight_number",
                    models.CharField(
                        help_text="Flight number", max_length=100, unique=True
                    ),
                ),
                (
                    "departure_airport",
                    models.CharField(help_text="Departure airport", max_length=100),
                ),
                (
                    "arrival_airport",
                    models.CharField(help_text="Arrival airport", max_length=100),
                ),
                ("departure_time", models.DateTimeField(help_text="Departure time")),
                ("arrival_time", models.DateTimeField(help_text="Arrival time")),
            ],
        ),
    ]
